version: '3'
services:
  app:
    build: 
     context: .
     dockerfile: ./docker/ruby/Dockerfile
    command: bundle exec ruby app.rb -o 0.0.0.0 
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user 
      MYSQL_PASSWORD: pass
